# Site settings
title: Om Nom Frickin Nom (dot) Com
email: your-email@domain.com
description: "Food"
baseurl: ""
url: "http://omnomfrickinnom.com"
twitter_username: coldclimate
github_username:  coldclimate

# Build settings
markdown: kramdown
permalink: pretty
