# Site settings
title: Om Nom Frickin Nom (dot) Com
email: Om Nom Frickin Nom (ats) coldclimate.co.uk
description: "Food"
baseurl: ""
url: "http://omnomfrickinnom.com"
twitter_username: coldclimate
github_username:  coldclimate

# Build settings
markdown: kramdown
permalink: pretty

# Excludes
exclude:
  - Vagrantfile
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - server
