name: master_pr_test
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SetupHugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.1/hugo_0.55.1_Linux-64bit.tar.gz
          tar -vzxf hugo_0.55.1_Linux-64bit.tar.gz
          chmod a+x hugo
      - name: Build
        run: ./hugo  --cleanDestinationDir  --gc
      - name: test
        run: vendor/htmltest/htmltest ./docs/ -c ./.htmltest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.OMNOM_KEY }}
          aws-secret-access-key: ${{ secrets.OMNOM_SECRET }}
          aws-region: eu-west-1
      - name: Copy files to the test website with the AWS CLI
        run: |
            aws s3 sync ./docs/ s3://preview.omnomfrickinnom.com --acl public-read --delete

name: master_push
on:
  push:
    branches:
      - 'master'
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SetupHugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.1/hugo_0.55.1_Linux-64bit.tar.gz
          tar -vzxf hugo_0.55.1_Linux-64bit.tar.gz
          chmod a+x hugo
      - name: Build
        run: ./hugo  --cleanDestinationDir  --gc
      - name: test
        run: vendor/htmltest/htmltest ./docs/ -c ./.htmltest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.OMNOM_KEY }}
          aws-secret-access-key: ${{ secrets.OMNOM_SECRET }}
          aws-region: eu-west-1
      - name: Copy files to the test website with the AWS CLI
        run: |
            aws s3 sync ./docs/ s3://www.omnomfrickinnom.com --acl public-read --delete